### ISSUE TITLE
ABOUT - colon

### ISSUE THREAD

**Issue by theemilyjones** [sowhatdoido/theemilyjones#13]
Please add a colon after 
Tweeting:
Photographing:
<img width="444" alt="screen shot 2017-03-14 at 10 20 35 pm" src="https://cloud.githubusercontent.com/assets/2328204/23934750/a01ed7c8-0904-11e7-813e-ec790dbcd3e9.png">

**Comment by sowhatdoido** [comment]
I added the colon and brought the icon into the anchor tag so that they get highlighted pink as well
