### ISSUE TITLE
Update Fresh Copy

### ISSUE THREAD

**Issue by theemilyjones** [sowhatdoido/theemilyjones#19]
****Hi bugs,

Can you update the copy for the Fresh Interactive work pop-up to the following? It needs to be present tense...I haven't left yet. Whoops.**** Thanks!!!

As a small but full-service interactive digital marketing agency that does all work in-house, I wore many hats at Fresh Interactive and learned the ins and outs of project management thoroughly and intimately.

My primary responsibility included overseeing the construction of new websites from conception and architecture all the way through design, programming, QA and client sign-off, in addition to being the day-to-day contact for retainer client requests ranging from eblast campaigns to new website campaigns. I’m the Fresh face for the client and the mastermind managing internal timetables and teams. But on any given day you may also find me handling the monthly billing reports, drafting new client proposals, QA testing eblast code, or image mapping in Photoshop.

**Comment by sowhatdoido** [comment]
Closing this out since it was done forever ago
