### ISSUE TITLE
Home Edits: Font corrections + Copy

### ISSUE THREAD

**Issue by theemilyjones** [sowhatdoido/theemilyjones#3]
- "Keeping LA..." is Raleway Black 60px, #333333

- Intro copy ("My name is Emily Jones...") is Karla Regular 16px, #4a4a4a

- Can you add "away from decaf" to the adjective rotator? (and the 100 emoji, if possible)

**Comment by sowhatdoido** [comment]
Ready for QA

**Comment by theemilyjones** [comment]
Put in a separate task for the 100 emoji. Closing out.

**Comment by theemilyjones** [comment]
"Keeping LA..." is Raleway Black 60px, #333333 (not Raleway bold)
