### ISSUE TITLE
Subtitles: Font + Spacing

### ISSUE THREAD

**Issue by theemilyjones** [sowhatdoido/theemilyjones#4]
All of the subtitles on the page are Raleway Regular 16px, all caps. They also have an extra space after each letter, ex: W O R K

This includes:
- A B O U T (#333333)
- W O R K (#d6008b)
- C A R E E R (#8e8e8e)
- V O L U N T E E R  +  E D U C A T I O N (correct this subtitle copy, #8e8e8e)
- C O N T A C T (#333333)

**Comment by sowhatdoido** [comment]
Ready for QA
